### ISSUE TITLE
WIP Feedback & enhancement for time series, monitoring network and locations management interface 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#803]
Prio 1: before release of 26st of may 
Prio 2: before or after release of 26st of may 

General: 
- [x] (Prio 1) the guiding texts have to be implemented @LirryPinter can you make a ticket for this? --> there are already 2 tickets for this issue: for the alarm form: https://github.com/nens/lizard-management-client/issues/779 and the timeseries: https://github.com/nens/lizard-management-client/issues/805 (DONE). Lirry is currently working on the help text for the alarm form.

- [x] (Prio 2) Currently a user can search for the uuid of a time series, monitoring network or location. However it's not very intuitive where they can find the uuid of the object. Can we add a UUID field to the form for existing objects (that have a uuid). We do something similar for label types, and i think with a little tweak we can apply this to time series, monitoring networks, locations, raster sources, raster layers, wms layers and 3di scenarios  --> A new issue is created for this: https://github.com/nens/lizard-management-client/issues/804
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/b3993d00-2347-42f3-bf66-b67455108548) 

Monitoring Network: 
- [x] (Prio 1): Currently the user can add time series to monitoring networks. This works very smooth. However, once added, a user can't track down what time series are added to the monitoring network. Can we add a listview of timeseries in the monitoring networks' form with a list of time series (maybe paginated) with a search bar. @hoanphungt  @LirryPinter maybe we can extend this list with removing time series from the monitoring network. --> related issue: https://github.com/nens/lizard-management-client/issues/713 which has been merged and deployed to staging

- [x] (Prio 1): Admin should be able to change the accesibility of a monitoring network. (A public time series can be added to a private monitoring network. This is fine as users without rights to the monitoring network won't see it in the catalogue.  A private time series can also be added to a public monitoring network which is also fine as users without rights won't see the specific time series) --> already done in this ticket: https://github.com/nens/lizard-management-client/issues/795

Time series: 
- [x] (Prio 1): User should be able the change accesibility of time series objects --> Updated the field to make it editable

Locations: 
- [x] (Prio 1): user should be able to change accesibiilty of location objects  --> already working correctly

**Comment by joeriverheijden** [comment]
@Derryrover @hoanphungt

**Comment by hoanphungt** [comment]
@joeriverheijden 
Hi Joeri, 

Thanks for making the ticket. I updated the description of the ticket and I am also gonna separate this ticket into different smaller tickets so we can easily estimate and work on them. 

Kr, Hoan

**Comment by hoanphungt** [comment]
For the tasks listed in this ticket, only the 2nd task is left over and a new issue has been created for it: https://github.com/nens/lizard-management-client/issues/804.

@lexvand Could you look at the priority of the above issue? (add UUID field to form with feature to copy it)
