### ISSUE TITLE
Geoblock graphical component in the geoblock build modal - part 3

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#984]
Based on the MVP, finish all the tasks:

**Tasks**

- [x] Horizontal vs vertical layout of view tabs (JSON text >> JSON editor >> Visual editor) (Tom vs Lirry) --> horizontal
- [x] JSON editor tab: icons for switch and pretty options --> new JSON library
- [x] Layout of a LizardRasterSource block --> name, dropdown and some metadata of the raster
- [x] Layout of a building block --> name and operation
- [x] New Block view: as in a column or in its own modal with search bar and more documentation? --> search bar and open block in a separate modal
- [x] Validation errors: how and where to show error messages? --> message bar and log tab if necessary
- [x] Option to edit/change an output block: with or without the +/- icons? --> without
- [x] Placement of default or constant values of a block (e.g. numbers): inside a building block or have its own input block? --> inside a building block
- [x] Fullscreen modal
- [x] Edge cases (e.g. coordinate array, enum type ...)

**MVP**

- JSON editor
- Geoblock visual editor
- Client-side validation for the graph: UUID of raster, orphan parts
- Back-end validation
- Validation UI
- Show cost per tile (waiting for backend)
- Fullscreen option - by default
- search bar for new blocks and more documentation on each block

**User stories**

- User should be able to create a new graph using the geoblock build modal
- User should be able to edit an existing graph of a geoblock using the geoblock build modal
- User should be able to view a geoblock in JSON format or in a visual editor
- User should be able to edit/create a graph using either the JSON editor or the visual editor
- User should be able to see if the graph is valid or not and why it is not valid

**Comment by hoanphungt** [comment]
Add 2 numbers together using Add returns 500 - internal server error

Using Group without inputting any block also returns 500
